#!/bin/zsh

case $1 in 
    "zsh")
        echo "Installing zsh config...."
        echo "\tLinking config files"
        cd ~
        ln -s ~/.config/dotfiles/zsh .zsh
        ln -s ~/.zsh/zshrc .zshrc
        echo "\tCloning oh-my-zsh-repo..."
        git clone https://github.com/robbyrussell/oh-my-zsh.git .oh-my-zsh
        echo "\tCloning zsh syntax highlighting repo..."
        git clone https://github.com/zsh-users/zsh-syntax-highlighting.git .zsh-syntax
        echo "Finished"
        ;;
esac
