#!/bin/bash

DIR=$HOME/Media/Wallpapers
image=$(sxiv -o -t -b $DIR)

if [ -z "$image" ]; then
    # No image selected, nothing to change
    exit 0
fi

wal "$@" -i "$image"
betterlockscreen -u "$image"
echo 'awesome.restart()' | awesome-client


