#!/bin/bash
DIR=$HOME/Media/Wallpapers
image=$(sxiv -o -t -b $DIR)

wal -i $image                                                              # Set the image as the background and recalculate the colorscheme
betterlockscreen -u $image                                                    # Update the image used on the lockscreen
notify-send -i $image "$(basename $image)" "Wallpaper & Lock Screen Updated"  # Send a notification when done.
