# Basic zsh configuration

# Fix tmux PATH issue
if [[ $TERM = "tmux-256color" ]]; then
    source ~/.zshenv
fi

unset GREP_OPTIONS
unsetopt nomatch

# Load my list of aliases
source $HOME/.zsh/aliases

# Load my taskwarrior specific settings
source $HOME/.zsh/taskwarrior

# Load fzf keybindings
source /usr/share/fzf/key-bindings.zsh

# Import antigen
source ~/.zsh-antigen/antigen.zsh

# Tell anitgen to use oh-my-zsh
antigen use oh-my-zsh

# Add bundles (from oh-my-zsh)
antigen bundle taskwarrior
antigen bundle vi-mode

# Add bundles (from other sources)
antigen bundle Tarrasch/zsh-bd
antigen bundle zsh-users/zsh-syntax-highlighting

# Load a prompt theme
antigen theme arrow

# Apply everything
antigen apply

autoload -U colors && colors

(cat ~/.cache/wal/sequences &)

# {{{ Functions
lst () { # Lists the contents of the dir in a single column unless there's too much in the dir
         # then it lists it in multiple columns

    if [[ $(ls -1 | wc -l) -gt 25 ]]; then
        ls -CFLsh --group-directories-first
    else
        ls -CFLsh1 --group-directories-first
    fi
}

cdl () {  # Clears the screen and list the contents of the directory just entered into

    if [[ $1 = '' ]]; then
        cd ~ && clear && lst
    else
        cd "$1" && clear && lst
    fi

}

gst() {
    git status --short
    git --no-pager diff --shortstat
}

function precmd()  # Prints an extra newline between commands which i think looks nicer
{
    echo
}
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export PATH=/home/alex/.local/bin:$PATH

# added by travis gem
[ -f /home/alex/.travis/travis.sh ] && source /home/alex/.travis/travis.sh

# tabtab source for electron-forge package
# uninstall by removing these lines or running `tabtab uninstall electron-forge`
[[ -f /home/alex/Projects/animation/anim8/node_modules/tabtab/.completions/electron-forge.zsh ]] && . /home/alex/Projects/animation/anim8/node_modules/tabtab/.completions/electron-forge.zsh
