# Basic zsh configuration

# Fix tmux PATH issue
if [[ $TERM = "tmux-256color" ]]; then
    source ~/.zshenv
fi

unset GREP_OPTIONS
unsetopt nomatch

# Import antigen
source ~/.zsh-antigen/antigen.zsh

# Tell anitgen to use oh-my-zsh
antigen use oh-my-zsh

# Add bundles (from oh-my-zsh)
antigen bundle taskwarrior
antigen bundle vi-mode

# Add bundles (from other sources)
antigen bundle Tarrasch/zsh-bd
antigen bundle zsh-users/zsh-syntax-highlighting

# Load a prompt theme
antigen theme arrow

# Apply everything
antigen apply

autoload -U colors && colors

# {{{ Functions
lst () { # Lists the contents of the dir in a single column unless there's too much in the dir
         # then it lists it in multiple columns

    if [[ $(ls -1 | wc -l) -gt 25 ]]; then
        ls -CFLsh --group-directories-first
    else
        ls -CFLsh1 --group-directories-first
    fi
}

cdl () {  # Clears the screen and list the contents of the directory just entered into

	if [[ $1 = '' ]]; then
		cd ~ && clear && lst
	else
		cd "$1" && clear && lst
	fi

}

testnet () { # Checks if internet is connected if not tells me to sort it
    ping -c 1 www.google.com
}


function precmd()  # Prints an extra newline between commands which i think looks nicer
{
	echo
}

function ts() # Handles sync and git backup of taskwarrior tasks
{
    cd $HOME/.task/
    task sync
    git add .
    git commit -m "Sync and backup"
    git push origin master
    cd -
}

function tick()
{
    due=$1
    shift
    task add +in +tickle wait:$due $@
}

function next()
{
    task $1 mod +next
}

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
