# Basic zsh configuration

unset GREP_OPTIONS

# Import antigen
source ~/.zsh-antigen/antigen.zsh

# Tell anitgen to use oh-my-zsh
antigen use oh-my-zsh

# Add bundles (from oh-my-zsh)
antigen bundle git
antigen bundle vi-mode

# Add bundles (from other sources)
antigen bundle Tarrasch/zsh-bd
antigen bundle zsh-users/zsh-syntax-highlighting

# Load a prompt theme
antigen theme frisk

# Apply everything
antigen apply

# Load my list of aliases
source $HOME/.zsh/aliases

# Command not found packge finder
source /usr/share/doc/pkgfile/command-not-found.zsh

# Enable vi mode line editing
bindkey -v
export KEYTIMEOUT=1

# Setting the timezone
TZ='Europe/London' ; export TZ

# Set a number of environment variables
export EDITOR='nvim'
export PATH=$PATH:$HOME/bin:$HOME/.gem/ruby/2.2.0/bin:$HOME/.cabal/bin:$HOME/.cask/bin
export LD_LIBRARY_PATH="/opt/java/jre/lib/amd64:/home/alex/.mylibs"
export MANPAGER="/bin/sh -c \"col -b | vim -u '~/.vim/vimrc_man' -c 'set ft=man ts=8 nomod nolist nonu noma fdm=indent' -\""

autoload -U colors && colors

# {{{ Functions
lst () { # Lists the contents of the dir in a single column unless there's too much in the dir
         # then it lists it in multiple columns

    if [[ $(ls -1 | wc -l) -gt 25 ]]; then
        ls -CFLsh --group-directories-first
    else
        ls -CFLsh1 --group-directories-first
    fi
}

cdl () {  # Clears the screen and list the contents of the directory just entered into

	if [[ $1 = '' ]]; then
		cd ~ && clear && lst
	else
		cd "$1" && clear && lst
	fi

}

testnet () { # Checks if internet is connected if not tells me to sort it
    ping -c 1 www.google.com
}


function precmd()  # Prints an extra newline between commands which i think looks nicer
{
	echo
}
