name: 'Docs'
on:
  push:
    branches:
    - main

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main

    - name: Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@main

    - name: Build Docs
      run: |
        nix build .

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: 'out'
        path: result/
